name: Zenn Post Scheduler
description: Publish an article of Zenn.
  It updates 'published' parameter in the article depending on target_key parameter (default 'published_at').
author: x-color
inputs:
  path:
    required: false
    description: A directory path for articles
    default: articles
  target_key:
    required: false
    description: A key of publication date
    default: published_at
  user:
    required: false
    description: Your Zenn account name. It's required if you want 'published_url'.
    default: ""
outputs:
  published:
    description: An list of published articles
  published_url:
    description: An list of published articles url
runs:
  using: node12
  main: dist/index.js
