name: test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
      - name: Edit 'published_at' in article files for the test
        run: |
          sed -i -e "s/<BEFORE 8H>/$(TZ='Asia/Tokyo' date -d '8 hours ago' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-before-8h.md
          sed -i -e "s/<TOMORROW>/$(TZ='Asia/Tokyo' date -d '1 days' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-tomorrow.md
          git add -u __tests__/data
      - name: Test the action
        uses: ./
        with:
          path: __tests__/data
        id: scheduler
      - name: Check the result
        run: |
          EXIT_CODE=0
          if [ "$(git diff --name-only __tests__/data/)" != "__tests__/data/published-at-before-8h.md" ]; then
            echo "Unexpected Diff"
            git diff __tests__/data/
            EXIT_CODE=1
          fi
          if [ "${{ join(fromJSON(steps.scheduler.outputs.published)) }}" != "__tests__/data/published-at-before-8h.md" ]; then
            echo "Unexpected Output('published')"
            echo ${{ steps.scheduler.outputs.published }}
            EXIT_CODE=1
          fi
          if [ "${{ fromJSON(steps.scheduler.outputs.published_url) }}" != "[]" ]; then
            echo "Unexpected Output('published_url')"
            echo ${{ steps.scheduler.outputs.published_url }}
            EXIT_CODE=1
          fi
          exit $EXIT_CODE
      - name: Revert changes
        if: always()
        run: git restore __tests__/data
      - name: Test the action with user input
        uses: ./
        with:
          path: __tests__/data
          user: dummy
        id: scheduler
      - name: Check the result
        run: |
          EXIT_CODE=0
          if [ "${{ join(fromJSON(steps.scheduler.outputs.published_url)) }}" != "https://zenn.dev/dummy/articles/published-at-before-8h" ]; then
            echo "Unexpected Output('published_url')"
            echo ${{ steps.scheduler.outputs.published_url }}
            EXIT_CODE=1
          fi
          exit $EXIT_CODE
