name: build-test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sed -i -e "s/<YESTERDAY>/$(TZ='Asia/Tokyo' date -d '1 days ago' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-yesterday.md
          sed -i -e "s/<TOMORROW>/$(TZ='Asia/Tokyo' date -d '1 days' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-tomorrow.md
      - uses: ./
        with:
          path: __tests__/data
      - run: |
          if [ "$(git diff --name-only __tests__/data/)" != "__tests__/data/published-at-yesterday.md" ]; then
            git diff __tests__/data/
            exit 1
          fi
