name: build-test
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sed -i -e "s//<BEFORE 8H>$(TZ='Asia/Tokyo' date -d '8 hours ago' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-before-8h.md
          sed -i -e "s/<TOMORROW>/$(TZ='Asia/Tokyo' date -d '1 days' '+%Y\/%m\/%d %H:%M:%S')/g" __tests__/data/published-at-tomorrow.md
          git add -u __tests__/data
      - uses: ./
        with:
          path: __tests__/data
        id: scheduler
      - run: |
          EXIT_CODE=0
          if [ "$(git diff --name-only __tests__/data/)" != "__tests__/data/published-at-before-8h.md" ]; then
            echo "Unexpected Diff"
            git diff __tests__/data/
            EXIT_CODE=1
          fi
          if [ "${{ steps.scheduler.outputs.published }}" != "__tests__/data/published-at-before-8h.md" ]; then
            echo "Unexpected Output"
            echo ${{ steps.scheduler.outputs.published }}
            EXIT_CODE=1
          fi
          exit $EXIT_CODE
